apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: mysql-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 062797229547.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
      imagePullSecrets:
        - name: regcred

