apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: webapp-ns
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: web-container
          image: 062797229547.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
          ports:
            - containerPort: 8080
          env: 
            - name: DBHOST
              value: "mysql"
            - name: DBPWD
              value: "root"
            - name: APP_COLOR
              value: "pink"
      imagePullSecrets:
        - name: regcred

