apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 062797229547.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
  imagePullSecrets:
    - name: regcred
