name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # ✅ Proper AWS credentials configuration
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # ✅ ECR login (uses credentials from above automatically)
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push WebApp Image
      run: |
        docker build -t ${{ secrets.ECR_WEBAPP_REPO }} ./webapp
        docker push ${{ secrets.ECR_WEBAPP_REPO }}

    - name: Build and Push MySQL Image
      run: |
        docker build -t ${{ secrets.ECR_MYSQL_REPO }} ./mysql
        docker push ${{ secrets.ECR_MYSQL_REPO }}
