apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835-sa
  namespace: fp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clo835
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clo835-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clo835
subjects:
  - kind: ServiceAccount
    name: clo835-sa
    namespace: fp
